title:              JBJ Blog
email:              qudwns4351@example.com
description:        안되면 될 때까지.
author:             JBJ Blog
baseurl:            ""
url:                "https://qudwns4351.github.io"

# Social Profiles
github_username:    https://github.com/qudwns4351

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
